### ISSUE TITLE
--config switch should support relative paths

### ISSUE THREAD

**Issue by AArnott** [dotnet/SignService#196]
When running the SignClient tool with ` -c .\azure-pipelines\SignClient.json`, this error was produced:

```
Exception: System.IO.FileNotFoundException: The configuration file 'azure-pipelines\SignClient.json' was not found and is not optional. The physical path is 'D:\git\Nerdbank.GitVersioning\bin\Nerdbank.GitVersioning.Tasks\Release\azure-pipelines\SignClient.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at SignClient.SignCommand.Sign(CommandOption configFile, CommandOption inputFile, CommandOption baseDirectory, CommandOption outputFile, CommandOption fileList, CommandOption clientSecret, CommandOption username, CommandOption name, CommandOption description, CommandOption descriptionUrl, CommandOption maxConcurrency) in d:\a\1\s\src\SignClient\SignCommand.cs:line 121
```

When I changed to `-c $pwd\azure-pipelines\SignClient.json` it worked fine.

Why don't relative paths work? Can that be fixed?

**Comment by onovotny** [comment]
Agree that it should but seem to recall issues in determining what the relative path was correctly. Happy to take a PR if you can?

**Comment by AArnott** [comment]
Oh, I guess I misunderstood what `--baseDirectory` was for. I assumed it only impacted `--input` but it evidently serves as the basis for *all* relative paths. So I guess this is by design.

**Comment by clairernovotny** [comment]
I needed that to make the wildcards work. Happy if there’s a better way to do this.

**Comment by AArnott** [comment]
Yes, I expected it was important for the pattern matching for `--inputs`, which is why I thought it would *only* influence that parameter, which is how I would have done it. 
Changing the behavior at this point would be a breaking change to the CLI. Since your recommended pattern involves installing the latest version of the dotnet CLI tool in the CI build, we can't afford to make *any* breaking changes or else all those CI systems may drop on the floor.

Consider changing the recommended pattern you point people to to actually pin the version of the tool folks install.
