### ISSUE TITLE
404 error from SignClient

### ISSUE THREAD

**Issue by andrewmolyneux** [dotnet/SignService#216]
I've got SignService deployed as an App Service and the back end looks fine. I used the admin interface to create a new account using the "Configured" option as the certificate I'm using is in a pre-existing key vault. I've configured my build pipeline to use the client but I get an error when I try to sign a file:

```
Submitting 'D:\a\1\s\bin\Release\<filename>.dll' for signing.
Error signing 'D:\a\1\s\bin\Release\<filename>.dll'
Server returned non Ok response: 404 Not Found
Exception: System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).) ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at SignClient.SignCommand.<>c__DisplayClass3_1.<Sign>b__1(FileInfo input) in D:\a\1\s\src\SignClient\SignCommand.cs:line 240
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at SignClient.SignCommand.Sign(CommandOption configFile, CommandOption inputFile, CommandOption baseDirectory, CommandOption outputFile, CommandOption fileList, CommandOption clientSecret, CommandOption username, CommandOption name, CommandOption description, CommandOption descriptionUrl, CommandOption maxConcurrency) in D:\a\1\s\src\SignClient\SignCommand.cs:line 178
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at SignClient.SignCommand.<>c__DisplayClass3_1.<Sign>b__1(FileInfo input) in D:\a\1\s\src\SignClient\SignCommand.cs:line 240
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
```

I'm almost certainly doing something wrong - any ideas?

**Comment by andrewmolyneux** [comment]
I've stepped through the SignClient code and the 404 error seems to be in response to a request for `https://<mySignServiceInstance>.azurewebsites.net/sign`. If I just send a GET request to this URL from a browser, I get a HTTP 405 response (Method Not Allowed) which makes sense as it's expecting a POST request. Seems a bit weird that it's returning 405 when I use the wrong method (implying that the resource exists but I'm using it incorrectly) but 404 when SignClient uses the correct method (indicating that the resource does not exist at all).

**Comment by andrewmolyneux** [comment]
I don't know if this is relevant, but if I open the Users page in the admin interface (`https://<mySignServiceInstance>.azurewebsites.net/Users`) and click the "Edit" link next to the user I created, I get a 404 error from that as well.

**Comment by andrewmolyneux** [comment]
I've been comparing the IAM properties for the `SignService-KeyVaults` resource group (created by InstallUtility) with the settings for the RG containing my key vault, and I noticed that `SignService-KeyVaults` has a role assignment ("Reader" for the `SignService Server` service principal) that wasn't present in my key vault. However, after adding that role assignment to my key vault I'm still getting the 404 errors.

**Comment by andrewmolyneux** [comment]
Hmm I've checked the `exceptions` table in Application Insights and it seems every failed signing request has a corresponding exception with problemId `Microsoft.Azure.KeyVault.Models.KeyVaultErrorException at SignService.Services.KeyVaultService+<GetCertificateAsync>d__16.MoveNext` - it seems there's still some issue with permissions as it's reporting "Operation returned an invalid status code 'Forbidden')". So it seems I'm still missing some security tweak on the key vault; I guess that wouldn't be necessary if I'd allowed SignService to create a new vault for me, but can somebody please point me towards the settings needed to allow access to an existing vault?

**Comment by andrewmolyneux** [comment]
Got it! The missing piece was on the "Access policies" blade for the key vault. I added an access policy with key permissions Get+Sign and certificate permissions Get, with the principal set to the user I created in SignService and the authorized application set to the `SignService Server` service principal, and now it seems it will sign files for me. I still get an error when I try to edit the user, but I'm not too concerned about that. Still, before I close this, if anyone can confirm that I'm not obviously doing something wildly wrong, that would be very much appreciated :)

**Comment by clairernovotny** [comment]
Seems right. For the service principal on the user issue, it seems like a permission is missing? The permissions are listed here: https://github.com/dotnet/SignService/blob/master/src/InstallUtility/Program.cs#L624-L628

Also, as it uses `Directory.AccessAsUser.All`, it requiers admin consent (click the "Grant Permissions" button in the Azure UI) and that the person using the service have permission/be in a role to edit the other users. This may mean being a Global Admin, User Administrator, or other similar role.

**Comment by andrewmolyneux** [comment]
I think the API permissions for the service principal are correct - after some fumbling around in the Azure portal I found this:
![service_principal_api_permissions](https://user-images.githubusercontent.com/5108077/78047382-2e631c00-7370-11ea-897a-6fd5da16b3a8.png)

I'll see if I can come up with some content for Administration.md that covers what I did. I don't think I've ever submitted a PR on GitHub before so this should be interesting :)
