### ISSUE TITLE
Signtool fails with Request was not processed because too many requests were received. Reason: VaultRequestTypeLimitReached

### ISSUE THREAD

**Issue by yowl** [dotnet/SignService#403]
Hi,

I'm just setting this up so probably have done something wrong, but when I get to running the SignClient it fails with 

```
C:\home\LogFiles\Application>type diagnostics-20210728.txt
2021-07-28 00:46:54.943 +00:00 [Error] SignService.AzureSignToolSignService: Error calling Key Vault
System.Security.Cryptography.CryptographicException: Error calling Key Vault
 ---> Azure.RequestFailedException: Service request failed.
Status: 429 ()

Content:
{"error":{"code":"Throttled","message":"Request was not processed because too many requests were received. Reason: VaultRequestTypeLimitReached"}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-keyvault-region: REDACTED
x-ms-client-request-id: 86428d0c-b724-43a9-a120-a159f6294bbd
x-ms-request-id: 3d0a75f1-128e-4bf5-8137-56fc976a0a6c
x-ms-keyvault-service-version: REDACTED
x-ms-keyvault-network-info: REDACTED
X-Powered-By: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Wed, 28 Jul 2021 00:46:54 GMT
Content-Length: 146
Content-Type: application/json; charset=utf-8
Expires: -1

   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequest(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequest[TContent,TResult](RequestMethod method, TContent content, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
   at Azure.Security.KeyVault.Keys.Cryptography.RemoteCryptographyClient.Sign(SignatureAlgorithm algorithm, Byte[] digest, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.Keys.Cryptography.CryptographyClient.Sign(SignatureAlgorithm algorithm, Byte[] digest, CancellationToken cancellationToken)
   at RSAKeyVaultProvider.KeyVaultContext.SignDigest(Byte[] digest, HashAlgorithmName hashAlgorithm, KeyVaultSignatureAlgorithm signatureAlgorithm) in /_/RSAKeyVaultProvider/KeyVaultContext.cs:line 95
   at RSAKeyVaultProvider.RSAKeyVault.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) in /_/RSAKeyVaultProvider/RSAKeyVault.cs:line 41
   --- End of inner exception stack trace ---
   at RSAKeyVaultProvider.RSAKeyVault.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) in /_/RSAKeyVaultProvider/RSAKeyVault.cs:line 45
   at AzureSign.Core.AuthenticodeKeyVaultSigner.SignCallback(IntPtr pCertContext, IntPtr pvExtra, UInt32 algId, Byte[] pDigestToSign, UInt32 dwDigestToSign, CRYPTOAPI_BLOB& blob)
   at AzureSign.Core.Interop.mssign32.SignerSignEx3(SignerSignEx3Flags dwFlags, SIGNER_SUBJECT_INFO* pSubjectInfo, SIGNER_CERT* pSignerCert, SIGNER_SIGNATURE_INFO* pSignatureInfo, IntPtr pProviderInfo, SignerSignTimeStampFlags dwTimestampFlags, Byte* pszTimestampAlgorithmOid, Char* pwszHttpTimeStamp, IntPtr psRequest, Void* pSipData, IntPtr* ppSignerContext, IntPtr pCryptoPolicy, SIGN_INFO* pSignInfo, IntPtr pReserved)
   at AzureSign.Core.AuthenticodeKeyVaultSigner.SignFile(ReadOnlySpan`1 path, ReadOnlySpan`1 description, ReadOnlySpan`1 descriptionUrl, Nullable`1 pageHashing, ILogger logger)
   at SignService.AzureSignToolSignService.RunSignTool(AuthenticodeKeyVaultSigner signer, String file, String description, String descriptionUrl) in E:\GitHub\SignService\src\SignService\SigningTools\AzureSignToolSignService.cs:line 107
2021-07-28 00:46:54.952 +00:00 [Error] SignService.AzureSignToolSignService: Sign tool completed with error 0
2021-07-28 00:46:59.986 +00:00 [Error] SignService.AzureSignToolSignService: Sign tool completed with error -2147024864
2021-07-28 00:47:01.007 +00:00 [Error] SignService.AzureSignToolSignService: Error calling Key Vault
System.Security.Cryptography.CryptographicException: Error calling Key Vault
 ---> Azure.RequestFailedException: Service request failed.
Status: 429 ()

Content:
{"error":{"code":"Throttled","message":"Request was not processed because too many requests were received. Reason: VaultRequestTypeLimitReached"}}

```

I'm attempting to sign an appx file using the command line
```
.\SignClient "Sign" `
      --baseDirectory "$(Build.SourcesDirectory)/src/Cms.Wpf/WapCms/AppPackages" `
      --input "**/*.appx" `
      --config "$(Build.SourcesDirectory)/src/SigningScripts/appsettings.json" `
      --user '$(SignClientUser)' `
      --secret '$(SignClientSecret)' `
      --name 'Cms'
```
If I look at the KeyVault I can see that there is a spike of activity which would agree with "too many requests":
![image](https://user-images.githubusercontent.com/2720041/127246569-932dc6e8-52b7-4b63-936c-780eda2702ae.png)

Any idea what I could have got wrong?

Thanks,

**Comment by yowl** [comment]
Looking here https://github.com/dotnet/SignService/blob/e485561013bc7f96d3e136b6d77e76a0db891f3a/src/SignService/SigningTools/SigningToolAggregate.cs#L110-L131  It seems that for appx files they are expanded and every file inside is passed to signing.  That would account for the large number of requests, but is that the right behaviour for signing an appx.  Shouldn't the appx itself be the file that is signed?

**Comment by clairernovotny** [comment]
It's a good idea to sign the files inside the bundle as well, but you should make sure it's only signing your files and not all the 3rd party ones inside. You can do that by specifying a filter file: 
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/main/Build/filelist.txt
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/main/azure-pipelines.yml#L269

**Comment by yowl** [comment]
I'm not using a bundle, ie. not an appxbundle, I'm only building a single rid so there's not much point in a bundle as I understand it.  I pass the appx in the input which I believe, reading https://docs.microsoft.com/en-us/windows/msix/package/sign-app-package-using-signtool is the only file which should be signed, although I could be wrong on that.  I dont think a filter will help as it will apply to the files inside the appx.

**Comment by clairernovotny** [comment]
When I say bundle, I include appx/msix as a bundle containing files. A filter will work on both the outer and inner files and is usually necessary with an appx/msix. 

It's a best practice to authenticode sign your files inside the appx and the service does that.

**Comment by yowl** [comment]
In which case its ok, just that the original problem, the large number of files causing KeyVault to fail.  I have 347 files in the appx and it seems each signing of the appx translates to around 600-700 requests to the KeyVault (according to insights).
![image](https://user-images.githubusercontent.com/2720041/127348483-94e927f9-7ea0-4287-8931-3e1921e9500d.png)
and that causes a VaultRequestTypeLimitReached error.  

I had a look at what we have in our dev setup where we sign using a test certificate and the command line

```
/target:Restore;WapCms:Publish /p:OutputPath=NonPackagedApp /p:UapAppxPackageBuildMode=SideLoadOnly  
/p:AppxBundle=Never  /p:AppxPackageSigningEnabled=true /p:SelfContained=True /p:RuntimeIdentifier=win-x86 
/p:PackageCertificateThumbprint="" /p:AppInstallerUri="http://dev.hubse.com/cmsinstalldev" 
/p:PackageCertificateKeyFile="$(signingcert.secureFilePath)" /p:PackageCertificatePassword=$(TestCodeSignCertPassword) 
/p:InformationalVersion=$(major).$(minor).$(build).$(revision)
```
I used signtool to check what gets signed.  For the appx this is signed by the test certificate:
```
C:\Windows\System32>"c:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe" verify /v e:\tmp\devappinstaller\WapCms_1.0.27.276_x86_Debug_Test\WapCms_1.0.27.276_x86_Debug.appx

Verifying: e:\tmp\devappinstaller\WapCms_1.0.27.276_x86_Debug_Test\WapCms_1.0.27.276_x86_Debug.appx

Signature Index: 0 (Primary Signature)
Hash of file (sha256): 4150505841585043....(cut)

Signing Certificate Chain:
    Issued to: Sxxxx
    Issued by: Sxxxx
    Expires:   Sun Jan 16 02:02:33 2022
    SHA1 hash: 44637E63....
```

I then pulled a file out of the appx at random, `Accessibility.dll` and ran the signtool on that and it's only signed by Microsoft:

```
C:\Windows\System32>"c:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe" verify /v e:\tmp\devappinstaller\WapCms_1.0.27.276_x86_Debug_Test\Accessibility.dll

Verifying: e:\tmp\devappinstaller\WapCms_1.0.27.276_x86_Debug_Test\Accessibility.dll

Signature Index: 0 (Primary Signature)
Hash of file (sha256): 179502136FAD49217796557D18A0DAE8B3AEFA4E68F541420CDE9BCCC3EB5E8A

Signing Certificate Chain:
    Issued to: Microsoft Root Certificate Authority 2011
    Issued by: Microsoft Root Certificate Authority 2011
    Expires:   Sat Mar 22 17:13:04 2036
    SHA1 hash: 8F43288AD272F3103B6FB1428485EA3014C0BCFE

        Issued to: Microsoft Code Signing PCA 2011
        Issued by: Microsoft Root Certificate Authority 2011
        Expires:   Wed Jul 08 16:09:09 2026
        SHA1 hash: F252E794FE438E35ACE6E53762C0A234A2C52135

            Issued to: Microsoft Corporation
            Issued by: Microsoft Code Signing PCA 2011
            Expires:   Thu Dec 02 16:31:45 2021
            SHA1 hash: ABDCA79AF9DD48A0EA702AD45260B3C03093FB4B

The signature is timestamped: Tue Jun 15 23:22:52 2021
Timestamp Verified by:
    Issued to: Microsoft Root Certificate Authority 2010
    Issued by: Microsoft Root Certificate Authority 2010
    Expires:   Sat Jun 23 17:04:01 2035
    SHA1 hash: 3B1EFD3A66EA28B16697394703A72CA340A05BD5

        Issued to: Microsoft Time-Stamp PCA 2010
        Issued by: Microsoft Root Certificate Authority 2010
        Expires:   Tue Jul 01 16:46:55 2025
        SHA1 hash: 2AA752FE64C49ABE82913C463529CF10FF2F04EE

            Issued to: Microsoft Time-Stamp Service
            Issued by: Microsoft Time-Stamp PCA 2010
            Expires:   Wed Jan 12 12:28:25 2022
            SHA1 hash: A04C15E8F4C630938C2935B1375329AF93CC90D4

SignTool Error: A certificate chain processed, but terminated in a root
        certificate which is not trusted by the trust provider.

Number of files successfully Verified: 0
Number of warnings: 0
Number of errors: 1
```

So it seems that msbuild only signs the appx which I can't get SignService to do out of the box.

**Comment by yowl** [comment]
I also tried on one of our files in the appx and that is not signed at all:
```
C:\Windows\System32>"c:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe" verify /v e:\tmp\devappinstaller\WapCms_1.0.27.276_x86_Debug_Test\Demurrage.dll

Verifying: e:\tmp\devappinstaller\WapCms_1.0.27.276_x86_Debug_Test\Demurrage.dll
SignTool Error: No signature found.

```

**Comment by clairernovotny** [comment]
SignTool doesn't recursively expand...it expects you to write the scripts to do that. SignService works differently and recursively signs what it can.

**Comment by yowl** [comment]
Sorry, I wasn't clear.  I'm not using signtool to sign, just to verify.  Trying to find out what I need SignService to do , to be the same or better than msbuild and to to fail on too many requests.

**Comment by clairernovotny** [comment]
You need to specify the filter file with the wildcards of your files.

**Comment by yowl** [comment]
Ok, I think we can close this one as it relates to too many files.  However there is subsequent problem in that when the appx is packed, it does not get signed which I think will make AppInstaller fail.  I will continue that in https://github.com/dotnet/SignService/issues/402

Thanks for the help
