### ISSUE TITLE
500 Error when submitting *.clickonce but only signs .exe when submitting *.zip

### ISSUE THREAD

**Issue by AdmiralP** [dotnet/SignService#410]
When we submit our *.clickonce file we get a 500 error (full error below). However, if we submit that same file using the .zip extension it signs only the *.exe files.

I am inclined to believe the issue lies in either our folder structure or in how our filelist.txt file is configured. Is there any further guidance available on the structure of the ClickOnce publish folder that is submitted and/or the filelist.txt structure?

Our folder is structured as follows:

- Root
  - Application Files (folder)
    - Application Version (folder) 
      - dlls
      - pdbs
      - application.exe.config.deploy
      - application.exe.deploy
      - application.exe.manifest
      - application.ico.deploy    
  - setup.exe
  - application.exe
  - application.manifest 

Our filelist.txt reads like this:

**/Setup.exe
**/applicationName.application
"Application Files"/**/applicationName.exe.manifest

```
C:\SignService\src\SignClient\bin\Debug\netcoreapp3.1\SignClient.exe : Error signing 'C:\Temp\ToSign\SignClient.clickonce'
At line:1 char:1
+ C:\SignService\src\SignClient\bin\Debug\netcoreapp3.1\SignClient.exe  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error signing '...ient.clickonce':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Server returned non Ok response: 500 Internal Server Error
Exception: System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 500 (Internal Server Error).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at SignClient.SignCommand.<>c__DisplayClass3_1.<Sign>b__3(FileInfo input) in C:\SignService\src\SignClient\SignCommand.cs:line 325
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 
localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, 
Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at SignClient.SignCommand.Sign(CommandOption configFile, CommandOption inputFile, CommandOption baseDirectory, CommandOption outputFile, CommandOption fileList, CommandOption clientSecret, CommandOption username, CommandOption name, CommandOption 
description, CommandOption descriptionUrl, CommandOption maxConcurrency, CommandOption loggingLevel) in C:\SignService\src\SignClient\SignCommand.cs:line 262
```

**Comment by tankerkiller125** [comment]
Can I ask what your solution was to this problem? We seem to be having the same issue with our setup and we haven't been able to solve it yet.

**Comment by KevinLPiatt** [comment]
> Can I ask what your solution was to this problem? We seem to be having the same issue with our setup and we haven't been able to solve it yet.

You will have to forgive me as it appears I left the error codes out of my comments.  In hindsight that was a terrible oversight.  

I will only really be able to provide you with the updates we made to overcome the various errors we encountered in the process.  

One issue was that we kept submitting our archive file as a .zip file and overlooked the fact that we needed to update the file extension to .clickonce before shipping it to SignService.  We added an Archive files task to our job, used the archive type of zip but created a .clickonce file.

Task type: Archive Files
Root folder to archive:
`$(build.artifactstagingdirectory)/publish/app.publish`
Archive Type:
`zip`
Archive file to create:
`$(Build.ArtifactStagingDirectory)/$(SignClientStaging)/$(Build.BuildId).clickonce`

As you can see from above, we are zipping the app.publish folder.  In our case this is: 
`C:\agent\_work\1\a\publish\app.publish `
You can adjust it to the appropriate _work directory.

In the final Authenticode (a PowerShell task) we found the need to explicitly reference the full path to SignClient.exe.  In our case this variable (SignClientPath) was set to: 
`C:\SignService\src\SignClient\bin\Debug\netcoreapp3.1\SignClient.exe`
We also needed to add the .clickonce extension to our input values in the Authenticode.

Here is our final PowerShell task for signing with Authenticode.  
Two things to note: 

1. I have broken syntax and added line breaks to make it easier to read but they would need to be removed
2. The single and double quotes are literals and are all part of the syntax that should not be removed

Task type: PowerShell
Type: Inline
Script:
```
$(SignClientPath) 'Sign'  
--baseDirectory '$(Build.ArtifactStagingDirectory)\$(SignClientStaging)' 
--input '**/*.{appxbundle,appinstaller,zip,nupkg,clickonce}' 
--config '$(SignServiceScripts)\appsettings.json' 
--user '$(SignServiceUser)' 
--secret '$(SignServiceSecret)' 
--name "Your Application Name" 
--description "Company Name" 
--descriptionUrl 'The URL used to deploy the app' 
--filelist '$(SignServiceScripts)\filelist.txt' 
--output '$(Build.ArtifactStagingDirectory)\$(SignClientShipping)'
```



We also had to make adjustments to our filelist.txt file in C:\SignService\scripts as we did not initially include the ApplicationName.exe.deploy:

```
**/setup.exe
**/ApplicationName.exe
**/ApplicationName.manifest
**/ApplicationName.application
**/ApplicationName.exe.deploy
```
