### ISSUE TITLE
SignFile fails with -2147024885

### ISSUE THREAD

**Issue by yowl** [dotnet/SignService#413]
I don't know what changed, but now the SignFile operation is failing with this error code which means bad format?  This happens for the command 
```
SIGN \WapCms_1.0.1000.68_x86.appx
```
The previous command is to sign the .appinstaller file which works.  From the pipeline log:
```
Submitting 'D:\a\1\s\src\Cms.Wpf\WapCms\AppPackages\Uat\WapCms_1.0.1000.68_x86_Test\WapCms_1.0.1000.68_x86.appx' for signing.
Submitting 'D:\a\1\s\src\Cms.Wpf\WapCms\AppPackages\Uat\WapCms_x86.appinstaller' for signing.
Successfully signed 'D:\a\1\s\src\Cms.Wpf\WapCms\AppPackages\Uat\WapCms_x86.appinstaller' in 18158 ms
Error signing 'D:\a\1\s\src\Cms.Wpf\WapCms\AppPackages\Uat\WapCms_1.0.1000.68_x86_Test\WapCms_1.0.1000.68_x86.appx'
Server returned non Ok response: 500 Internal Server Error
Exception: System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 500 (Internal Server Error).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at SignClient.SignCommand.<>c__DisplayClass3_1.<Sign>b__3(FileInfo input) in /_/src/SignClient/SignCommand.cs:line 319
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
```
In AppInsights the error code -2147024885 is seen:

![image](https://user-images.githubusercontent.com/2720041/132692533-24b63612-c6a0-4f40-8a4c-7e579d75e43e.png)

But I don't know where to go from here.

**Comment by yowl** [comment]
I ran the SignService locally with the appx built locally and it succeeded, unfortunately.

**Comment by yowl** [comment]
Well, seems like D1 service plan is not enough anymore to sign my appx, Worked last week, but I changed to B1 and the pipeline has started working again.  Seems excessive for signing one app every now and then, but there must have been some limit on the file size or something, even though I was well under the quotas shown in the Azure portal.  If I wasn't so cynical I'd think this was just a money grab.
